services:
  db:
    image: postgres:18
    restart: unless-stopped
    container_name: xmoto-web-db
    shm_size: 128mb

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - xmoto-web-db:/var/lib/postgresql

volumes:
  xmoto-web-db:
